### ISSUE TITLE
Add new persian reference for django beginner

### ISSUE THREAD

**Issue by TorhamDev** [DjangoEx/python-engineer-roadmap#77]
### I Want to Request the Following Reference(s) To Be Archived Publically
> Add as many references as you want to be archived in the repository in the following pattern.
- [mongard django beginners](https://www.mongard.ir/courses/django-beginners/) (persian) (free)

> License approvement aggregation.
- [ ] All my mentioned references approve the [qualification parameters](https://github.com/DjangoEx/python-engineer-roadmap/blob/main/CONTRIBUTING.md#qualified-references).

**Comment by lnxpy** [comment]
Since the language mark and paid/free accessibility is patched, we don't include them in the archive. People can check on themselves. That would be so cool if you reopen the same issue on [djangoex/python-engineer-roadmap-persian](https://github.com/DjangoEx/python-engineer-roadmap-persian).

Thanks mate you absolute lovely contributor. <3 :))
